/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Song16.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\byb\Desktop\xbf.txt                    *
* Read pattern file: C:\Users\byb\Desktop\xbf.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSong16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __X_____,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  _____XX_,
  ______X_,
  ______X_,
  ______X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ____XXXX,
  ___X___X,
  ___X____,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____XX__,
  ________,
  ________};

/* Start of unicode area <General Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_2020[ 16] = { /* code 2020, DAGGER */
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________};

/* Start of unicode area <Box Drawing> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_2525[ 32] = { /* code 2525, BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

/* Start of unicode area <CJK Symbols and Punctuation> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3025[ 32] = { /* code 3025, HANGZHOU NUMERAL FIVE */
  ________,________,
  _____X__,___X____,
  _____X__,___X____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___XXXX_,_X______,
  _______X,X_______,
  ______X_,_X______,
  _____X__,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  _____X__,_X______,
  ______XX,X_______,
  ________,________};

/* Start of unicode area <Bopomofo> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_310A[ 32] = { /* code 310A, BOPOMOFO LETTER T */
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  ____X___,__X_____,
  ___XXXXX,XXXX____,
  ________,____X___,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3120[ 32] = { /* code 3120, BOPOMOFO LETTER AU */
  ________,________,
  ______X_,________,
  ______X_,________,
  _____X__,__X_____,
  _____X__,__X_____,
  ____X___,_X______,
  ____X___,_X______,
  ___XXXXX,X_______,
  _______X,________,
  ______X_,________,
  _____X__,_X______,
  ____X___,__X_____,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,________,
  ________,________};

/* Start of unicode area <Hangul> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3534[ 32] = { /* code 3534 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X______,________,
  _X__XXXX,XXXXX___,
  _X__X___,X___X___,
  _X__XXXX,XXXXX___,
  _X__X___,X___X___,
  _X__XXXX,XXXXX___,
  _X____X_,__X_____,
  _X__XXXX,XXXXX___,
  _X____X_,__X_____,
  _X_XXXXX,XXXXXX__,
  _X___X__,___X____,
  _X__X___,____X___,
  _XXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3736[ 32] = { /* code 3736 */
  __X____X,XXXX____,
  __X___X_,___X____,
  __X__XXX,XXXXXX__,
  __X___X_,_____X__,
  XXXXX_XX,XXXXXX__,
  _X__X_X_,__X__X__,
  _X__X_XX,X_XXX___,
  _X__X_X_,__X___X_,
  _X__X__X,XXXXXXX_,
  X__X__X_,___X____,
  _X_X_XXX,XXXXXX__,
  __X___X_,_X___X__,
  __XX__XX,XXXXXX__,
  _X__X___,XX_X____,
  _X__X__X,_X__X_X_,
  X____XX_,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3938[ 32] = { /* code 3938 */
  ___X____,_X______,
  ___X____,_X______,
  ___X__XX,XXXXXX__,
  ___XX___,_X______,
  _X_X_X__,_X______,
  _X_X____,_X______,
  _X_X_XXX,XXXXXXX_,
  X__X____,X__X____,
  ___X__X_,X__X_X__,
  ___X__X_,X__X__X_,
  ___X_X__,X__X__X_,
  ___XX__X,___X__X_,
  ___X___X,___X____,
  ___X__X_,___X____,
  ___X_X__,_X_X____,
  ___XX___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_3AC6[ 32] = { /* code 3AC6 */
  __X_____,__X_____,
  ___X____,__X_____,
  ________,_X_X____,
  XXXXXXX_,_X_X____,
  __X_____,X___X___,
  __X____X,_____X__,
  __XXXXX_,__X___X_,
  __X__X__,__X_____,
  __X__X__,X_X_X___,
  __X__X__,X_X__X__,
  __X__X_X,__X__X__,
  __X__X_X,__X___X_,
  _X___XX_,__X___X_,
  _X_X_X__,__X_____,
  X___X___,X_X_____,
  ________,_X______};

/* Start of unicode area <Hangul Supplementary-A> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_414C[ 32] = { /* code 414C */
  ____X___,________,
  ___XXX__,XXXXXX__,
  XXXX____,X____X__,
  ___X____,X____X__,
  ___X____,XXXXXX__,
  XXXXXX__,________,
  ___X___X,XXXXXXX_,
  __XX___X,______X_,
  __XXX__X,______X_,
  _X_X_X_X,XXXXXXX_,
  _X_X_X_X,______X_,
  X__X___X,______X_,
  ___X___X,XXXXXXX_,
  ___X___X,______X_,
  ___X___X,____X_X_,
  ___X___X,_____X__};

/* Start of unicode area <Hangul Supplementary-A and B> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4453[ 32] = { /* code 4453 */
  ____X___,__X_____,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_XXXXXX,XXXXXX__,
  ____X___,__X_____,
  ___XXXXX,XXXX____,
  _______X,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _XXXXXXX,XXXXXX__};

/* Start of unicode area <Hangul Supplementary-B> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4620[ 32] = { /* code 4620 */
  __X_____,_X______,
  ___X____,_X______,
  ________,_X______,
  XXXXXX__,_X______,
  ____X__X,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  __XX_X__,X____X__,
  _X_XX___,X_X__X__,
  X__X_X__,X_X__X__,
  ___X_X_X,__X_X___,
  ___X___X,__X_X___,
  ___X__X_,___X____,
  ___X_X__,__X_X___,
  ___X____,_X___X__,
  ___X___X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4853[ 32] = { /* code 4853 */
  ___X___X,________,
  ___X___X,________,
  __X____X,___XXX__,
  _X___XXX,XX______,
  X______X,________,
  ___X_XXX,XX______,
  __X__X_X,_XXXXXX_,
  _XX__XXX,XX__X___,
  X_X__X_X,_X__X___,
  __X__XXX,XX__X___,
  __X____X,____X___,
  __X_XXXX,XXX_X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,__X_X___,
  __X____X,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4950[ 32] = { /* code 4950 */
  ________,__X_____,
  _XXXXXX_,_XXXXX__,
  ___X_X__,XX___X__,
  ____X___,__XXX___,
  XXXXXXX_,XX___XX_,
  __X_X_X_,__X_____,
  _X__X___,XXXXXX__,
  X_X_X___,_X___X__,
  ___X___X,X___XX__,
  _____XX_,XX______,
  ___XX___,__XX____,
  XXX_XXXX,XXX_XXX_,
  _______X,________,
  __XXXXXX,XXXXX___,
  ____X__X,__X_____,
  XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4C46[ 32] = { /* code 4C46 */
  __X_____,________,
  __X____X,XXXXXX__,
  _XXXX___,_X___X__,
  _X__X___,_X__X___,
  X__X____,X___XXX_,
  _XXXXX__,X_____X_,
  _X_X_X_X,_XXXX_X_,
  _X_X_XX_,___X_X__,
  _XXXXX__,__X_____,
  _X_X_X__,__X_____,
  _X_X_XXX,XXXXXXX_,
  _XXXXX__,__X_____,
  ________,__X_____,
  X_X_X_X_,__X_____,
  X_X_X_X_,X_X_____,
  ________,_X______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4E0D[ 32] = { /* code 4E0D */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ________,X_______,
  ________,X_______,
  _______X,________,
  _______X,________,
  ______XX,_X______,
  _____X_X,__X_____,
  ____X__X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X_____X,_____X__,
  X______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4E2D[ 32] = { /* code 4E2D */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4EF6[ 32] = { /* code 4EF6 */
  ____X___,__X_____,
  ____X___,__X_____,
  ____X__X,__X_____,
  ___X___X,__X_____,
  ___X___X,XXXXXX__,
  __XX__X_,__X_____,
  __XX__X_,__X_____,
  _X_X_X__,__X_____,
  X__X____,__X_____,
  ___X_XXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4F59[ 32] = { /* code 4F59 */
  _______X,________,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_XXXX,XXX_X___,
  XX_____X,_____XX_,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  __X____X,_____X__,
  _X___X_X,_____X__,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4F7F[ 32] = { /* code 4F7F */
  ___X____,_X______,
  ___X____,_X______,
  ___XXXXX,XXXXXXX_,
  __X_____,_X______,
  __X_____,_X______,
  _XX__XXX,XXXXXX__,
  _XX__X__,_X___X__,
  X_X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  __X___X_,_X______,
  __X____X,_X______,
  __X_____,X_______,
  __X____X,_X______,
  __X___X_,__XX____,
  __X_XX__,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_4FDD[ 32] = { /* code 4FDD */
  ____X___,________,
  ____X_XX,XXXXX___,
  ____X_X_,____X___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  __XX__XX,XXXXX___,
  __XX____,_X______,
  _X_X____,_X______,
  X__X_XXX,XXXXXX__,
  ___X____,XXX_____,
  ___X___X,_X_X____,
  ___X__X_,_X__X___,
  ___X_X__,_X___X__,
  ___XX___,_X____X_,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5053[ 32] = { /* code 5053 */
  ____X___,________,
  ____X_XX,XXXXXX__,
  ____X_X_,_____X__,
  ___X__X_,_____X__,
  ___X__XX,XXXXXX__,
  __XX__X_,________,
  __XX__XX,XXXXXX__,
  _X_X__X_,_X______,
  X__X__X_,X___X___,
  ___X__XX,XXXXXX__,
  ___X__X_,__X__X__,
  ___X__X_,__X_____,
  ___X_X_X,XXXXXX__,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  ___X__XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_50A8[ 32] = { /* code 50A8 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___XX___,XXXXX_X_,
  __X__X__,__X__X__,
  __X__X__,__X_X___,
  _XX____X,XXXXXXX_,
  _XX_____,__X_____,
  X_XXXX__,_X______,
  __X__X__,XXXXXX__,
  __X__X_X,_X___X__,
  __X__XX_,_X___X__,
  __X__X__,_XXXXX__,
  __X__X_X,_X___X__,
  __X__XX_,_X___X__,
  __X__X__,_XXXXX__,
  __X_____,_X___X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5165[ 32] = { /* code 5165 */
  _____X__,________,
  ______X_,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,___X____,
  _X______,____X___,
  X_______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5176[ 32] = { /* code 5176 */
  ____X___,__X_____,
  ____X___,__X_____,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____XXXX,XXX_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5230[ 32] = { /* code 5230 */
  ________,_____X__,
  XXXXXXXX,X____X__,
  ____X___,_____X__,
  ___X____,__X__X__,
  __X___X_,__X__X__,
  _X_____X,__X__X__,
  XXXXXXXX,X_X__X__,
  ____X___,X_X__X__,
  ____X___,__X__X__,
  ____X___,__X__X__,
  _XXXXXXX,__X__X__,
  ____X___,__X__X__,
  ____X___,_____X__,
  ____XXXX,X____X__,
  XXXXX___,___X_X__,
  _X______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5236[ 32] = { /* code 5236 */
  _____X__,_____X__,
  __X__X__,_____X__,
  __X__X__,_____X__,
  __XXXXXX,X_X__X__,
  _X___X__,__X__X__,
  _____X__,__X__X__,
  XXXXXXXX,XXX__X__,
  _____X__,__X__X__,
  _____X__,__X__X__,
  __XXXXXX,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__XX_,X____X__,
  __X__X_X,_____X__,
  _____X__,___X_X__,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_524D[ 32] = { /* code 524D */
  ___X____,___X____,
  ____X___,___X____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  __XXXXX_,____X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __XXXXX_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __XXXXX_,_X__X___,
  __X___X_,____X___,
  __X___X_,____X___,
  __X_X_X_,__X_X___,
  __X__X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5269[ 32] = { /* code 5269 */
  _____XXX,______X_,
  _XXXX___,______X_,
  ____X___,______X_,
  XXXXXXXX,X_____X_,
  __X_X_X_,___X__X_,
  __X_X_X_,X__X__X_,
  XXX_X_XX,___X__X_,
  __X_X_X_,X__X__X_,
  _XX_X_X_,X__X__X_,
  X_X_X__X,X__X__X_,
  ___XXX__,___X__X_,
  __X_X_X_,___X__X_,
  _X__X__X,______X_,
  X___X___,X_____X_,
  ____X___,____X_X_,
  ____X___,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5320[ 32] = { /* code 5320 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X______,________,
  _X______,__XXX___,
  _X___XXX,XX______,
  _X___X__,________,
  _X___X__,________,
  _X___XXX,XXXXXX__,
  _X___X__,__X_____,
  _X___X__,__X_____,
  _X___X__,__X_____,
  _X__X___,__X_____,
  _X__X___,__X_____,
  _X_X____,__X_____,
  _XXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5341[ 32] = { /* code 5341 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5361[ 32] = { /* code 5361 */
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_53D8[ 32] = { /* code 53D8 */
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,_X______,
  ___X_X__,_X_X____,
  __X__X__,_X__X___,
  _X___X__,_X___X__,
  ________,________,
  __XXXXXX,XXXX____,
  ____X___,__X_____,
  _____X__,_X______,
  ______X_,X_______,
  _______X,________,
  _____XX_,XX______,
  ___XX___,__XX____,
  XXX_____,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_540E[ 32] = { /* code 540E */
  ________,___X____,
  ________,XXXXX___,
  ___XXXXX,________,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXXX_,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  ___X_XXX,XXXXX___,
  ___X_X__,____X___,
  __X__X__,____X___,
  __X__X__,____X___,
  _X___X__,____X___,
  X____XXX,XXXXX___,
  _____X__,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_590D[ 32] = { /* code 590D */
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXX__,
  __X_____,________,
  _X_XXXXX,XXXX____,
  X__X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  _____X__,________,
  ____XXXX,XXXX____,
  ___XX___,__X_____,
  _XX__X__,_X______,
  ______XX,X_______,
  ___XXX__,_XXX____,
  XXX_____,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5931[ 32] = { /* code 5931 */
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  __XXXXXX,XXXXX___,
  __X____X,________,
  _X_____X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_59CB[ 32] = { /* code 59CB */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,_X______,
  XXXXXX__,_X__X___,
  __X__X__,X____X__,
  __X__X_X,XXXXXXX_,
  __X__X__,X_____X_,
  __X__X__,________,
  _X__X___,XXXXXX__,
  __X_X___,X____X__,
  ___X____,X____X__,
  __X_X___,X____X__,
  _X___X__,X____X__,
  X_______,XXXXXX__,
  ________,X____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5B57[ 32] = { /* code 5B57 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ___XXXXX,XXX_____,
  ________,_X______,
  ________,X_______,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5B58[ 32] = { /* code 5B58 */
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ____X___,________,
  ___X__XX,XXXXX___,
  ___X____,___X____,
  __XX____,__X_____,
  _X_X____,_X______,
  X__X_XXX,XXXXXXX_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X___X,_X______,
  ___X____,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5B8C[ 32] = { /* code 5B8C */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,_X___X__,
  ____X___,_X___X__,
  ___X____,_X___X__,
  _XX_____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5B9E[ 32] = { /* code 5B9E */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X___X___,X____X__,
  _____X__,X_______,
  _____X__,X_______,
  ___X____,X_______,
  ____X___,X_______,
  ____X___,X_______,
  XXXXXXXX,XXXXXXX_,
  _______X,_X______,
  ______X_,__X_____,
  _____X__,___X____,
  ___XX___,____X___,
  _XX_____,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5C06[ 32] = { /* code 5C06 */
  ____X___,X_______,
  ____X___,XXXXX___,
  ____X__X,____X___,
  _X__X_X_,___X____,
  __X_X___,X_X_____,
  __X_X___,_X______,
  ____X___,X__X____,
  ____X_XX,___X____,
  ___XX___,___X____,
  __X_X_XX,XXXXXXX_,
  XX__X___,___X____,
  ____X__X,___X____,
  ____X___,X__X____,
  ____X___,___X____,
  ____X___,_X_X____,
  ____X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5DF2[ 32] = { /* code 5DF2 */
  ________,________,
  __XXXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,________,
  __X_____,________,
  __X_____,________,
  __X_____,_____X__,
  __X_____,_____X__,
  __X_____,_____X__,
  ___XXXXX,XXXXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5E93[ 32] = { /* code 5E93 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X____X,________,
  __X____X,________,
  __XXXXXX,XXXXXX__,
  __X___X_,________,
  __X__X__,X_______,
  __X_X___,X_______,
  __X_XXXX,XXXXX___,
  __X_____,X_______,
  __X_____,X_______,
  _X_XXXXX,XXXXXXX_,
  _X______,X_______,
  X_______,X_______,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5F00[ 32] = { /* code 5F00 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_5F53[ 32] = { /* code 5F53 */
  _______X,________,
  __X____X,____X___,
  ___X___X,____X___,
  ____X__X,___X____,
  ____X__X,__X_____,
  _______X,________,
  _XXXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  _XXXXXXX,XXXXX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6210[ 32] = { /* code 6210 */
  ________,_X_X____,
  ________,_X__X___,
  ________,_X______,
  __XXXXXX,XXXXXXX_,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X___X__,
  __XXXXX_,_X___X__,
  __X___X_,_X___X__,
  __X___X_,__X_X___,
  __X___X_,__X_X___,
  __X___X_,___X__X_,
  __X_X_X_,__XX__X_,
  _X___X__,_X__X_X_,
  _X______,X____XX_,
  X______X,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_622E[ 32] = { /* code 622E */
  ________,___X____,
  _XXX_XXX,___X_X__,
  ___X___X,___X__X_,
  _X_X_X_X,___X____,
  __XX__XX,___X_XX_,
  _X_X_X_X,_XXXX___,
  ____XX__,___X__X_,
  __XX__XX,___X__X_,
  XX___X__,X__X__X_,
  ___XX___,___X_X__,
  _XX___X_,___X_X__,
  ____XX__,X___X___,
  _XXX___X,___XX_X_,
  _____XX_,__X_X_X_,
  ___XX___,_X___XX_,
  XXX_____,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6253[ 32] = { /* code 6253 */
  ___X____,________,
  ___X____,________,
  ___X__XX,XXXXXXX_,
  ___X____,__X_____,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  __XX____,__X_____,
  XX_X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _X_X____,X_X_____,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6432[ 32] = { /* code 6432 */
  __X_____,X_______,
  __X_____,_X______,
  __X__XXX,XXXXXX__,
  __X__X__,_____X__,
  XXXXX__X,___X____,
  __X___X_,____X___,
  __X_____,__XXXX__,
  __X_X_XX,XX_X____,
  __XX__X_,X__X____,
  XXX___X_,X__X____,
  __X___X_,X__X____,
  __X___X_,X___X___,
  __X___X_,X___X___,
  __X__X__,X_X__X__,
  X_X__X__,XX_X_X__,
  _X__X___,X__X__X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_653E[ 32] = { /* code 653E */
  __X_____,_X______,
  ___X____,_X______,
  ________,_X______,
  XXXXXXX_,X_______,
  __X_____,XXXXXXX_,
  __X____X,____X___,
  __XXXXX_,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X__X__,_X_X____,
  __X__X__,_X_X____,
  __X__X__,__X_____,
  _X___X__,_X_X____,
  _X_X_X__,X___X___,
  X___X__X,_____X__,
  ______X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6587[ 32] = { /* code 6587 */
  ______X_,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ___X____,___X____,
  ___X____,___X____,
  ____X___,__X_____,
  ____X___,__X_____,
  _____X__,_X______,
  ______X_,X_______,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_65E0[ 32] = { /* code 65E0 */
  ________,________,
  __XXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXXXX__,
  _____X__,X_______,
  _____X__,X_______,
  _____X__,X_______,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X____X__,
  __X_____,X____X__,
  _X______,_XXXXX__,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_660A[ 32] = { /* code 660A */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____X__,_X______,
  ___XX___,__XX____,
  XXX_____,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_677F[ 32] = { /* code 677F */
  ___X____,____X___,
  ___X____,___XXX__,
  ___X___X,XXX_____,
  ___X___X,________,
  XXXXXX_X,________,
  ___X___X,XXXXXX__,
  __XX___X,_X___X__,
  __XXX__X,_X___X__,
  _X_X_X_X,_X___X__,
  _X_X_X_X,__X_X___,
  X__X___X,__X_X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X__X_,__X_X___,
  ___X__X_,_X___X__,
  ___X_X__,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6962[ 32] = { /* code 6962 */
  ___X___X,____X___,
  ___X____,X___X___,
  ___X____,X__X____,
  ___X_XXX,XXXXXXX_,
  XXXXX___,X__X____,
  ___X____,X__X____,
  __XX__XX,XXXXXX__,
  __XXX_X_,X__X_X__,
  _X_X_XX_,X__X_X__,
  _X_X__XX,____XX__,
  X__X__X_,_____X__,
  ___X__XX,XXXXXX__,
  ___X__X_,_____X__,
  ___X__X_,_____X__,
  ___X__XX,XXXXXX__,
  ___X__X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6CD5[ 32] = { /* code 6CD5 */
  ________,_X______,
  __X_____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  X____XXX,XXXXXX__,
  _X______,_X______,
  _X______,_X______,
  ___X____,_X______,
  ___XXXXX,XXXXXXX_,
  __X_____,_X______,
  XXX_____,X_______,
  __X____X,________,
  __X___X_,___X____,
  __X__X__,____X___,
  __X_XXXX,XXXXXX__,
  _____X__,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6E69[ 32] = { /* code 6E69 */
  ________,____X___,
  __X_____,__XXXX__,
  ___X_XXX,XX______,
  ___X____,_X______,
  X___XXXX,XXXXXXX_,
  _X______,_X______,
  _X___XXX,XXXXXX__,
  ___X_X__,_X___X__,
  ___X_XXX,XXXXXX__,
  __X__X__,_X___X__,
  XXX__XXX,XXXXXX__,
  __X_____,_X______,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6E6F[ 32] = { /* code 6E6F */
  ________,________,
  __X___XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  X_____X_,____X___,
  _X____XX,XXXXX___,
  _X_X____,________,
  ___XXXXX,XXXXXXX_,
  ___X__X_,________,
  __X___XX,XXXXXX__,
  XXX__X__,X__X_X__,
  __X_X__X,__X__X__,
  __X___X_,_X___X__,
  __X__X__,X____X__,
  __X____X,__X_X___,
  ______X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_6F66[ 32] = { /* code 6F66 */
  ________,_X______,
  __X_____,_X______,
  ___X_XXX,XXXXXX__,
  ___X____,X_X_____,
  X____X_X,___X_X__,
  _X____X_,____X___,
  _X___XXX,XXXXXX__,
  ___XX_X_,____X_X_,
  ___X__XX,XXXXX___,
  __X___X_,____X___,
  XXX___XX,XXXXX___,
  __X_____,_X______,
  __X___X_,_X__X___,
  __X__X__,_X___X__,
  __X_X__X,_X___X__,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_746E[ 32] = { /* code 746E */
  ________,________,
  ______XX,XXXXXXX_,
  XXXXX___,_X_X____,
  __X_____,_X_X____,
  __X___XX,XXXXXXX_,
  __X___X_,_X_X__X_,
  __X___X_,_X_X__X_,
  XXXXX_XX,XXXXXXX_,
  __X_____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  __XXX___,_XXX____,
  XXX_____,X_X_X___,
  _X_____X,__X__X__,
  _____XX_,__X___X_,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_7528[ 32] = { /* code 7528 */
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  _X_____X,____X___,
  _X_____X,__X_X___,
  X_______,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_79D2[ 32] = { /* code 79D2 */
  ____X___,__X_____,
  ___XXX__,__X_____,
  XXXX____,__X_____,
  ___X____,X_X_X___,
  ___X____,X_X__X__,
  XXXXXX__,X_X___X_,
  ___X___X,__X___X_,
  __XX___X,__X_____,
  __XXX_X_,__X__X__,
  _X_X_X__,__X__X__,
  _X_X_X__,__X_X___,
  X__X____,____X___,
  ___X____,___X____,
  ___X____,__X_____,
  ___X____,XX______,
  ___X__XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_7ECF[ 32] = { /* code 7ECF */
  ___X____,________,
  ___X___X,XXXXXX__,
  __X_____,____X___,
  __X__X__,___X____,
  _X___X__,__XX____,
  XXXXX___,_X__X___,
  ___X____,X____X__,
  __X___XX,______X_,
  _X______,________,
  XXXXXX_X,XXXXXX__,
  _X______,__X_____,
  ________,__X_____,
  ___XXX__,__X_____,
  XXX_____,__X_____,
  _X____XX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_8BC1[ 32] = { /* code 8BC1 */
  ________,________,
  __X_____,________,
  ___X__XX,XXXXXXX_,
  ___X____,__X_____,
  ________,__X_____,
  ________,__X_____,
  XXXX___X,__X_____,
  ___X___X,__X_____,
  ___X___X,__XXXX__,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X_X_X,__X_____,
  ___XX__X,__X_____,
  ___X___X,__X_____,
  _____XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_8D25[ 32] = { /* code 8D25 */
  ________,_X______,
  _XXXXX__,_X______,
  _X___X__,_X______,
  _X_X_X__,X_______,
  _X_X_X__,XXXXXXX_,
  _X_X_X_X,____X___,
  _X_X_XX_,X___X___,
  _X_X_X__,X___X___,
  _X_X_X__,X___X___,
  _X_X_X__,_X_X____,
  _X_X_X__,_X_X____,
  ___X____,__X_____,
  __X_X___,_X_X____,
  __X__X__,X___X___,
  _X___X_X,_____X__,
  X_____X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_8F7D[ 32] = { /* code 8F7D */
  ____X___,__X_____,
  ____X___,__X_X___,
  _XXXXXXX,__X__X__,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ___X____,__X_____,
  ___X____,__X__X__,
  XXXXXXXX,__X__X__,
  __X_____,__X__X__,
  _X__X___,__X_X___,
  _XXXXXXX,__X_X___,
  ____X___,___X____,
  ____XXXX,___X__X_,
  XXXXX___,__X_X_X_,
  ____X___,_X___XX_,
  ____X___,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_8FD8[ 32] = { /* code 8FD8 */
  ________,________,
  __X___XX,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ________,_X______,
  ________,_X______,
  XXXX____,XX_X____,
  ___X___X,_X__X___,
  ___X__X_,_X___X__,
  ___X_X__,_X___X__,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSong16_9A8C[ 32] = { /* code 9A8C */
  ________,__X_____,
  XXXXX___,__X_____,
  ____X___,_X_X____,
  _X__X___,_X_X____,
  _X__X___,X___X___,
  _X__X__X,_____X__,
  _X__X_X_,XXXXX_X_,
  _XXXXX__,________,
  _____X__,_X___X__,
  _____X__,__X__X__,
  ___XXX_X,__X__X__,
  XXX__X__,X_X_X___,
  _X___X__,X___X___,
  _____X__,___X____,
  __X_X_XX,XXXXXXX_,
  ___X____,________};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_FontSong16_FF0C[ 32] = { /* code FF0C, FULLWIDTH COMMA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ___X____,________,
  __X_____,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSong16_CharInfo[100] = {
   {   8,   8,  1, acGUI_FontSong16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_FontSong16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_FontSong16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_FontSong16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontSong16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontSong16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontSong16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontSong16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontSong16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontSong16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontSong16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontSong16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontSong16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontSong16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontSong16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_FontSong16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontSong16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_FontSong16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontSong16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_FontSong16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_FontSong16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_FontSong16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontSong16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_FontSong16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontSong16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_FontSong16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_FontSong16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_FontSong16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_FontSong16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_FontSong16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontSong16_2020 } /* code 2020 */
  ,{  16,  16,  2, acGUI_FontSong16_2525 } /* code 2525 */
  ,{  16,  16,  2, acGUI_FontSong16_3025 } /* code 3025 */
  ,{  16,  16,  2, acGUI_FontSong16_310A } /* code 310A */
  ,{  16,  16,  2, acGUI_FontSong16_3120 } /* code 3120 */
  ,{  16,  16,  2, acGUI_FontSong16_3534 } /* code 3534 */
  ,{  16,  16,  2, acGUI_FontSong16_3736 } /* code 3736 */
  ,{  16,  16,  2, acGUI_FontSong16_3938 } /* code 3938 */
  ,{  16,  16,  2, acGUI_FontSong16_3AC6 } /* code 3AC6 */
  ,{  16,  16,  2, acGUI_FontSong16_414C } /* code 414C */
  ,{  16,  16,  2, acGUI_FontSong16_4453 } /* code 4453 */
  ,{  16,  16,  2, acGUI_FontSong16_4620 } /* code 4620 */
  ,{  16,  16,  2, acGUI_FontSong16_4853 } /* code 4853 */
  ,{  16,  16,  2, acGUI_FontSong16_4950 } /* code 4950 */
  ,{  16,  16,  2, acGUI_FontSong16_4C46 } /* code 4C46 */
  ,{  16,  16,  2, acGUI_FontSong16_4E0D } /* code 4E0D */
  ,{  16,  16,  2, acGUI_FontSong16_4E2D } /* code 4E2D */
  ,{  16,  16,  2, acGUI_FontSong16_4EF6 } /* code 4EF6 */
  ,{  16,  16,  2, acGUI_FontSong16_4F59 } /* code 4F59 */
  ,{  16,  16,  2, acGUI_FontSong16_4F7F } /* code 4F7F */
  ,{  16,  16,  2, acGUI_FontSong16_4FDD } /* code 4FDD */
  ,{  16,  16,  2, acGUI_FontSong16_5053 } /* code 5053 */
  ,{  16,  16,  2, acGUI_FontSong16_50A8 } /* code 50A8 */
  ,{  16,  16,  2, acGUI_FontSong16_5165 } /* code 5165 */
  ,{  16,  16,  2, acGUI_FontSong16_5176 } /* code 5176 */
  ,{  16,  16,  2, acGUI_FontSong16_5230 } /* code 5230 */
  ,{  16,  16,  2, acGUI_FontSong16_5236 } /* code 5236 */
  ,{  16,  16,  2, acGUI_FontSong16_524D } /* code 524D */
  ,{  16,  16,  2, acGUI_FontSong16_5269 } /* code 5269 */
  ,{  16,  16,  2, acGUI_FontSong16_5320 } /* code 5320 */
  ,{  16,  16,  2, acGUI_FontSong16_5341 } /* code 5341 */
  ,{  16,  16,  2, acGUI_FontSong16_5361 } /* code 5361 */
  ,{  16,  16,  2, acGUI_FontSong16_53D8 } /* code 53D8 */
  ,{  16,  16,  2, acGUI_FontSong16_540E } /* code 540E */
  ,{  16,  16,  2, acGUI_FontSong16_590D } /* code 590D */
  ,{  16,  16,  2, acGUI_FontSong16_5931 } /* code 5931 */
  ,{  16,  16,  2, acGUI_FontSong16_59CB } /* code 59CB */
  ,{  16,  16,  2, acGUI_FontSong16_5B57 } /* code 5B57 */
  ,{  16,  16,  2, acGUI_FontSong16_5B58 } /* code 5B58 */
  ,{  16,  16,  2, acGUI_FontSong16_5B8C } /* code 5B8C */
  ,{  16,  16,  2, acGUI_FontSong16_5B9E } /* code 5B9E */
  ,{  16,  16,  2, acGUI_FontSong16_5C06 } /* code 5C06 */
  ,{  16,  16,  2, acGUI_FontSong16_5DF2 } /* code 5DF2 */
  ,{  16,  16,  2, acGUI_FontSong16_5E93 } /* code 5E93 */
  ,{  16,  16,  2, acGUI_FontSong16_5F00 } /* code 5F00 */
  ,{  16,  16,  2, acGUI_FontSong16_5F53 } /* code 5F53 */
  ,{  16,  16,  2, acGUI_FontSong16_6210 } /* code 6210 */
  ,{  16,  16,  2, acGUI_FontSong16_622E } /* code 622E */
  ,{  16,  16,  2, acGUI_FontSong16_6253 } /* code 6253 */
  ,{  16,  16,  2, acGUI_FontSong16_6432 } /* code 6432 */
  ,{  16,  16,  2, acGUI_FontSong16_653E } /* code 653E */
  ,{  16,  16,  2, acGUI_FontSong16_6587 } /* code 6587 */
  ,{  16,  16,  2, acGUI_FontSong16_65E0 } /* code 65E0 */
  ,{  16,  16,  2, acGUI_FontSong16_660A } /* code 660A */
  ,{  16,  16,  2, acGUI_FontSong16_677F } /* code 677F */
  ,{  16,  16,  2, acGUI_FontSong16_6962 } /* code 6962 */
  ,{  16,  16,  2, acGUI_FontSong16_6CD5 } /* code 6CD5 */
  ,{  16,  16,  2, acGUI_FontSong16_6E69 } /* code 6E69 */
  ,{  16,  16,  2, acGUI_FontSong16_6E6F } /* code 6E6F */
  ,{  16,  16,  2, acGUI_FontSong16_6F66 } /* code 6F66 */
  ,{  16,  16,  2, acGUI_FontSong16_746E } /* code 746E */
  ,{  16,  16,  2, acGUI_FontSong16_7528 } /* code 7528 */
  ,{  16,  16,  2, acGUI_FontSong16_79D2 } /* code 79D2 */
  ,{  16,  16,  2, acGUI_FontSong16_7ECF } /* code 7ECF */
  ,{  16,  16,  2, acGUI_FontSong16_8BC1 } /* code 8BC1 */
  ,{  16,  16,  2, acGUI_FontSong16_8D25 } /* code 8D25 */
  ,{  16,  16,  2, acGUI_FontSong16_8F7D } /* code 8F7D */
  ,{  16,  16,  2, acGUI_FontSong16_8FD8 } /* code 8FD8 */
  ,{  16,  16,  2, acGUI_FontSong16_9A8C } /* code 9A8C */
  ,{  16,  16,  2, acGUI_FontSong16_FF0C } /* code FF0C */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop87 = {
   0xFF0C /* first character */
  ,0xFF0C /* last character  */
  ,&GUI_FontSong16_CharInfo[ 99] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop86 = {
   0x9A8C /* first character */
  ,0x9A8C /* last character  */
  ,&GUI_FontSong16_CharInfo[ 98] /* address of first character */
  ,&GUI_FontSong16_Prop87 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop85 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 97] /* address of first character */
  ,&GUI_FontSong16_Prop86 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop84 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontSong16_CharInfo[ 96] /* address of first character */
  ,&GUI_FontSong16_Prop85 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop83 = {
   0x8D25 /* first character */
  ,0x8D25 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 95] /* address of first character */
  ,&GUI_FontSong16_Prop84 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop82 = {
   0x8BC1 /* first character */
  ,0x8BC1 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 94] /* address of first character */
  ,&GUI_FontSong16_Prop83 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop81 = {
   0x7ECF /* first character */
  ,0x7ECF /* last character  */
  ,&GUI_FontSong16_CharInfo[ 93] /* address of first character */
  ,&GUI_FontSong16_Prop82 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop80 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 92] /* address of first character */
  ,&GUI_FontSong16_Prop81 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop79 = {
   0x7528 /* first character */
  ,0x7528 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 91] /* address of first character */
  ,&GUI_FontSong16_Prop80 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop78 = {
   0x746E /* first character */
  ,0x746E /* last character  */
  ,&GUI_FontSong16_CharInfo[ 90] /* address of first character */
  ,&GUI_FontSong16_Prop79 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop77 = {
   0x6F66 /* first character */
  ,0x6F66 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 89] /* address of first character */
  ,&GUI_FontSong16_Prop78 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop76 = {
   0x6E6F /* first character */
  ,0x6E6F /* last character  */
  ,&GUI_FontSong16_CharInfo[ 88] /* address of first character */
  ,&GUI_FontSong16_Prop77 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop75 = {
   0x6E69 /* first character */
  ,0x6E69 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 87] /* address of first character */
  ,&GUI_FontSong16_Prop76 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop74 = {
   0x6CD5 /* first character */
  ,0x6CD5 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 86] /* address of first character */
  ,&GUI_FontSong16_Prop75 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop73 = {
   0x6962 /* first character */
  ,0x6962 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 85] /* address of first character */
  ,&GUI_FontSong16_Prop74 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop72 = {
   0x677F /* first character */
  ,0x677F /* last character  */
  ,&GUI_FontSong16_CharInfo[ 84] /* address of first character */
  ,&GUI_FontSong16_Prop73 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop71 = {
   0x660A /* first character */
  ,0x660A /* last character  */
  ,&GUI_FontSong16_CharInfo[ 83] /* address of first character */
  ,&GUI_FontSong16_Prop72 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop70 = {
   0x65E0 /* first character */
  ,0x65E0 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 82] /* address of first character */
  ,&GUI_FontSong16_Prop71 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop69 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 81] /* address of first character */
  ,&GUI_FontSong16_Prop70 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop68 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontSong16_CharInfo[ 80] /* address of first character */
  ,&GUI_FontSong16_Prop69 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop67 = {
   0x6432 /* first character */
  ,0x6432 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 79] /* address of first character */
  ,&GUI_FontSong16_Prop68 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop66 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 78] /* address of first character */
  ,&GUI_FontSong16_Prop67 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop65 = {
   0x622E /* first character */
  ,0x622E /* last character  */
  ,&GUI_FontSong16_CharInfo[ 77] /* address of first character */
  ,&GUI_FontSong16_Prop66 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop64 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 76] /* address of first character */
  ,&GUI_FontSong16_Prop65 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop63 = {
   0x5F53 /* first character */
  ,0x5F53 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 75] /* address of first character */
  ,&GUI_FontSong16_Prop64 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop62 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 74] /* address of first character */
  ,&GUI_FontSong16_Prop63 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop61 = {
   0x5E93 /* first character */
  ,0x5E93 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 73] /* address of first character */
  ,&GUI_FontSong16_Prop62 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop60 = {
   0x5DF2 /* first character */
  ,0x5DF2 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 72] /* address of first character */
  ,&GUI_FontSong16_Prop61 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop59 = {
   0x5C06 /* first character */
  ,0x5C06 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 71] /* address of first character */
  ,&GUI_FontSong16_Prop60 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop58 = {
   0x5B9E /* first character */
  ,0x5B9E /* last character  */
  ,&GUI_FontSong16_CharInfo[ 70] /* address of first character */
  ,&GUI_FontSong16_Prop59 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop57 = {
   0x5B8C /* first character */
  ,0x5B8C /* last character  */
  ,&GUI_FontSong16_CharInfo[ 69] /* address of first character */
  ,&GUI_FontSong16_Prop58 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop56 = {
   0x5B57 /* first character */
  ,0x5B58 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 67] /* address of first character */
  ,&GUI_FontSong16_Prop57 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop55 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSong16_CharInfo[ 66] /* address of first character */
  ,&GUI_FontSong16_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop54 = {
   0x5931 /* first character */
  ,0x5931 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 65] /* address of first character */
  ,&GUI_FontSong16_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop53 = {
   0x590D /* first character */
  ,0x590D /* last character  */
  ,&GUI_FontSong16_CharInfo[ 64] /* address of first character */
  ,&GUI_FontSong16_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop52 = {
   0x540E /* first character */
  ,0x540E /* last character  */
  ,&GUI_FontSong16_CharInfo[ 63] /* address of first character */
  ,&GUI_FontSong16_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop51 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 62] /* address of first character */
  ,&GUI_FontSong16_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop50 = {
   0x5361 /* first character */
  ,0x5361 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 61] /* address of first character */
  ,&GUI_FontSong16_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop49 = {
   0x5341 /* first character */
  ,0x5341 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 60] /* address of first character */
  ,&GUI_FontSong16_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop48 = {
   0x5320 /* first character */
  ,0x5320 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 59] /* address of first character */
  ,&GUI_FontSong16_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop47 = {
   0x5269 /* first character */
  ,0x5269 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 58] /* address of first character */
  ,&GUI_FontSong16_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop46 = {
   0x524D /* first character */
  ,0x524D /* last character  */
  ,&GUI_FontSong16_CharInfo[ 57] /* address of first character */
  ,&GUI_FontSong16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop45 = {
   0x5236 /* first character */
  ,0x5236 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 56] /* address of first character */
  ,&GUI_FontSong16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop44 = {
   0x5230 /* first character */
  ,0x5230 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 55] /* address of first character */
  ,&GUI_FontSong16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop43 = {
   0x5176 /* first character */
  ,0x5176 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 54] /* address of first character */
  ,&GUI_FontSong16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop42 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 53] /* address of first character */
  ,&GUI_FontSong16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop41 = {
   0x50A8 /* first character */
  ,0x50A8 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 52] /* address of first character */
  ,&GUI_FontSong16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop40 = {
   0x5053 /* first character */
  ,0x5053 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 51] /* address of first character */
  ,&GUI_FontSong16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop39 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontSong16_CharInfo[ 50] /* address of first character */
  ,&GUI_FontSong16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop38 = {
   0x4F7F /* first character */
  ,0x4F7F /* last character  */
  ,&GUI_FontSong16_CharInfo[ 49] /* address of first character */
  ,&GUI_FontSong16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop37 = {
   0x4F59 /* first character */
  ,0x4F59 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 48] /* address of first character */
  ,&GUI_FontSong16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop36 = {
   0x4EF6 /* first character */
  ,0x4EF6 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 47] /* address of first character */
  ,&GUI_FontSong16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop35 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontSong16_CharInfo[ 46] /* address of first character */
  ,&GUI_FontSong16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop34 = {
   0x4E0D /* first character */
  ,0x4E0D /* last character  */
  ,&GUI_FontSong16_CharInfo[ 45] /* address of first character */
  ,&GUI_FontSong16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop33 = {
   0x4C46 /* first character */
  ,0x4C46 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 44] /* address of first character */
  ,&GUI_FontSong16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop32 = {
   0x4950 /* first character */
  ,0x4950 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 43] /* address of first character */
  ,&GUI_FontSong16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop31 = {
   0x4853 /* first character */
  ,0x4853 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 42] /* address of first character */
  ,&GUI_FontSong16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop30 = {
   0x4620 /* first character */
  ,0x4620 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 41] /* address of first character */
  ,&GUI_FontSong16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop29 = {
   0x4453 /* first character */
  ,0x4453 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 40] /* address of first character */
  ,&GUI_FontSong16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop28 = {
   0x414C /* first character */
  ,0x414C /* last character  */
  ,&GUI_FontSong16_CharInfo[ 39] /* address of first character */
  ,&GUI_FontSong16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop27 = {
   0x3AC6 /* first character */
  ,0x3AC6 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 38] /* address of first character */
  ,&GUI_FontSong16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop26 = {
   0x3938 /* first character */
  ,0x3938 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 37] /* address of first character */
  ,&GUI_FontSong16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop25 = {
   0x3736 /* first character */
  ,0x3736 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 36] /* address of first character */
  ,&GUI_FontSong16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop24 = {
   0x3534 /* first character */
  ,0x3534 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 35] /* address of first character */
  ,&GUI_FontSong16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop23 = {
   0x3120 /* first character */
  ,0x3120 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 34] /* address of first character */
  ,&GUI_FontSong16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop22 = {
   0x310A /* first character */
  ,0x310A /* last character  */
  ,&GUI_FontSong16_CharInfo[ 33] /* address of first character */
  ,&GUI_FontSong16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop21 = {
   0x3025 /* first character */
  ,0x3025 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 32] /* address of first character */
  ,&GUI_FontSong16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop20 = {
   0x2525 /* first character */
  ,0x2525 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 31] /* address of first character */
  ,&GUI_FontSong16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop19 = {
   0x2020 /* first character */
  ,0x2020 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 30] /* address of first character */
  ,&GUI_FontSong16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop18 = {
   0x0074 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 29] /* address of first character */
  ,&GUI_FontSong16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop17 = {
   0x006E /* first character */
  ,0x006F /* last character  */
  ,&GUI_FontSong16_CharInfo[ 27] /* address of first character */
  ,&GUI_FontSong16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop16 = {
   0x0069 /* first character */
  ,0x0069 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 26] /* address of first character */
  ,&GUI_FontSong16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop15 = {
   0x0066 /* first character */
  ,0x0066 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 25] /* address of first character */
  ,&GUI_FontSong16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop14 = {
   0x0064 /* first character */
  ,0x0064 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 24] /* address of first character */
  ,&GUI_FontSong16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop13 = {
   0x0062 /* first character */
  ,0x0062 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 23] /* address of first character */
  ,&GUI_FontSong16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop12 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 22] /* address of first character */
  ,&GUI_FontSong16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop11 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 21] /* address of first character */
  ,&GUI_FontSong16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop10 = {
   0x004C /* first character */
  ,0x004C /* last character  */
  ,&GUI_FontSong16_CharInfo[ 20] /* address of first character */
  ,&GUI_FontSong16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop9 = {
   0x0048 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 18] /* address of first character */
  ,&GUI_FontSong16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop8 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontSong16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop7 = {
   0x0044 /* first character */
  ,0x0044 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 16] /* address of first character */
  ,&GUI_FontSong16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop6 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontSong16_CharInfo[ 15] /* address of first character */
  ,&GUI_FontSong16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop5 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontSong16_CharInfo[  4] /* address of first character */
  ,&GUI_FontSong16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop4 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontSong16_CharInfo[  3] /* address of first character */
  ,&GUI_FontSong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop3 = {
   0x002C /* first character */
  ,0x002C /* last character  */
  ,&GUI_FontSong16_CharInfo[  2] /* address of first character */
  ,&GUI_FontSong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontSong16_CharInfo[  1] /* address of first character */
  ,&GUI_FontSong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSong16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontSong16_CharInfo[  0] /* address of first character */
  ,&GUI_FontSong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

