/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Yahei.c                                               *
* Font:        ËÎÌå                                                  *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Documents and Settings\Administrator\×ÀÃæ\Q.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYahei;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontYahei_0020[ 40] = { /* code 0020, SPACE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_0031[ 40] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  __XXXX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_003A[ 40] = { /* code 003A, COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontYahei_4E09[ 60] = { /* code 4E09 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_______X,XX______,
  ___XXXXX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,______XX,X_______,
  ____XXXX,XXXXXXX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_XX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_4EBA[ 60] = { /* code 4EBA */
  ________,________,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XXX____,________,
  ________,_XXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XX_XX___,________,
  ________,XX_XX___,________,
  _______X,XX__XX__,________,
  _______X,X___XX__,________,
  ______XX,X____XX_,________,
  ______XX,_____XXX,________,
  _____XX_,______XX,X_______,
  ____XX__,_______X,XXX_____,
  __XXX___,________,XXX_____,
  _XX_____,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_4FE1[ 60] = { /* code 4FE1 */
  ________,________,________,
  _____XXX,___XX___,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,_XX_____,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,________,
  ___XXX__,________,XX______,
  ___XXX__,XXXXXXXX,X_______,
  __XXXX__,________,________,
  _XX_XX__,_______X,XX______,
  ____XX__,XXXXXXXX,________,
  ____XX__,________,________,
  ____XX__,XXXXXXXX,XX______,
  ____XX__,XX_____X,X_______,
  ____XX__,XX_____X,X_______,
  ____XX__,XX_____X,X_______,
  ____XX__,XXXXXXXX,X_______,
  ____XX__,XX_____X,XX______,
  ____XX__,XX_____X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_522B[ 60] = { /* code 522B */
  ________,________,________,
  ________,________,_XX_____,
  ___XXXXX,XXXX____,_XX_____,
  ___XX___,_XX_____,_XX_____,
  ___XX___,_XX__XX_,_XX_____,
  ___XX___,_XX__XX_,_XX_____,
  ___XXXXX,XXX__XX_,_XX_____,
  ___XXXX_,_XX__XX_,_XX_____,
  ______XX,_____XX_,_XX_____,
  ______XX,_____XX_,_XX_____,
  ______XX,__XX_XX_,_XX_____,
  __XXXXXX,XXXX_XX_,_XX_____,
  _____XX_,__XX_XX_,_XX_____,
  _____XX_,__XX_XX_,_XX_____,
  _____XX_,_XXX____,_XX_____,
  ____XX__,_XXX____,_XX_____,
  ___XX___,_XX_____,_XX_____,
  __XX___X,XXX___XX,XXX_____,
  _XX_____,XX______,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_53F7[ 60] = { /* code 53F7 */
  ________,________,________,
  _____XX_,______XX,________,
  _____XXX,XXXXXXXX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XXX,XXXXXXXX,________,
  _____XX_,________,________,
  ________,________,XXX_____,
  __XXXXXX,XXXXXXXX,X_______,
  _______X,X_______,________,
  ______XX,_______X,X_______,
  ______XX,XXXXXXXX,X_______,
  ________,______XX,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,_____XXX,________,
  ________,__XXXXX_,________,
  ________,___XXX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_540D[ 60] = { /* code 540D */
  ________,________,________,
  ________,XX______,________,
  ________,XX______,________,
  _______X,X______X,X_______,
  ______XX,XXXXXXXX,XX______,
  ______XX,______XX,________,
  _____XXX,X____XXX,________,
  ____XX_X,XX__XXX_,________,
  ___XX___,XX_XXX__,________,
  ________,__XX____,________,
  ________,_XX_____,________,
  _______X,XX______,XX______,
  _____XXX,XXXXXXXX,XX______,
  ____XX_X,X_______,XX______,
  _XXXX__X,X_______,XX______,
  _______X,X_______,XX______,
  _______X,X_______,XX______,
  _______X,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_5438[ 60] = { /* code 5438 */
  ________,________,________,
  ________,________,________,
  _______X,XXXXXXXX,X_______,
  __XXXXXX,_XXX__XX,________,
  __XX_XX_,_XX___XX,________,
  __XX_XX_,_XX__XXX,________,
  __XX_XX_,_XX__XX_,________,
  __XX_XX_,_XXX_XXX,XX______,
  __XX_XX_,_XXX___X,XX______,
  __XX_XX_,_XXX___X,X_______,
  __XX_XX_,_XXXX__X,X_______,
  __XXXXX_,XX_XX_XX,X_______,
  __XX_XXX,XX__XXXX,________,
  __XX____,XX___XXX,________,
  _______X,X____XX_,________,
  ______XX,____XXXX,X_______,
  _____XX_,__XXX__X,XXX_____,
  ____XX__,_XX_____,_XX_____,
  _______X,XX______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_547C[ 60] = { /* code 547C */
  ________,________,________,
  ________,________,XX______,
  ________,_____XXX,XX______,
  __XX__XX,XXXXXXX_,________,
  __XXXXXX,_____XX_,________,
  __XX__XX,XX___XX_,_XXX____,
  __XX__XX,_XX__XX_,XX______,
  __XX__XX,_XXX_XXX,X_______,
  __XX__XX,__XX_XX_,________,
  __XX__XX,_____XX_,_XX_____,
  __XX__XX,XXXXXXXX,XXXX____,
  __XX__XX,_____XX_,________,
  __XXXXXX,_____XX_,________,
  __XX__XX,_____XX_,________,
  __XX____,_____XX_,________,
  ________,_____XX_,________,
  ________,____XXX_,________,
  ________,__XXXX__,________,
  ________,____XX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_578B[ 60] = { /* code 578B */
  ________,________,________,
  ________,________,XXX_____,
  __XXXXXX,XXXX____,XX______,
  _____XX_,XX___XXX,XX______,
  _____XX_,XX___XX_,XX______,
  _____XX_,XX___XX_,XX______,
  __XXXXXX,XXXXXXX_,XX______,
  _____XX_,XX__XXX_,XX______,
  ____XXX_,XX___XX_,XX______,
  ____XX__,XX______,XX______,
  ____XX__,XX___XX_,XX______,
  ___XX___,XX____XX,XX______,
  _XXX____,__XX____,________,
  ________,__XX___X,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ________,__XX____,________,
  ________,__XX____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_59D3[ 60] = { /* code 59D3 */
  ________,________,________,
  ____XXX_,_____XX_,________,
  ____XXX_,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,__XX_XX_,________,
  ____XX_X,X_XX_XX_,_XX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ___XX__X,XXX__XX_,________,
  ___XX__X,XX___XX_,________,
  ___XX_XX,XX___XX_,________,
  __XX__XX,_____XX_,________,
  __XX__XX,_XXXXXXX,XXX_____,
  __XX__XX,_____XX_,________,
  ___XXXX_,_____XX_,________,
  _____XXX,X____XX_,________,
  ____XX_X,XX___XX_,________,
  ___XX___,_____XX_,________,
  __XX____,_____XX_,_XXX____,
  _XX_____,_XXXXXXX,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_5E8A[ 60] = { /* code 5E8A */
  ________,________,________,
  ________,__XX____,________,
  ________,__XXX___,________,
  ___XX___,________,_XX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,__XXX___,________,
  ___XX___,__XX____,________,
  ___XX___,__XX____,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,_XXXX___,________,
  ___XX___,_XXXXX__,________,
  ___XX___,XXXX_XX_,________,
  __XX___X,X_XX_XX_,________,
  __XX___X,X_XX__XX,________,
  __XX__XX,__XX__XX,X_______,
  __XX_XX_,__XX___X,XXX_____,
  _XX_XX__,__XX____,_XX_____,
  _XXXX___,__XX____,________,
  ________,__XX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_5F20[ 60] = { /* code 5F20 */
  ________,________,________,
  ________,__XX____,________,
  _XXXXXXX,X_XX____,________,
  ______XX,__XX___X,XX______,
  ______XX,__XX__XX,X_______,
  ______XX,__XX__XX,________,
  __XX__XX,__XX_XX_,________,
  __XXXXXX,__XXXX__,________,
  __XX____,__XX____,________,
  __XX___X,XXXXXXXX,XXX_____,
  __XXXXXX,__XXXX__,________,
  ______XX,__XX_XX_,________,
  ______XX,__XX_XX_,________,
  _____XX_,__XX__XX,________,
  _____XX_,__XX__XX,X_______,
  _____XX_,__XX_XXX,XX______,
  _____XX_,__XXXX__,XXX_____,
  __XXXX__,__XXX___,________,
  ___XX___,__XX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_5FC3[ 60] = { /* code 5FC3 */
  ________,________,________,
  ________,________,________,
  ________,_XX_____,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ______XX,___XXX__,________,
  ______XX,X__XX___,________,
  ______XX,X______X,X_______,
  ______XX,X_______,XX______,
  ___XX_XX,X_______,XXX_____,
  ___XX_XX,X_______,_XX_____,
  __XXX_XX,X_______,_XXX____,
  _XXXX_XX,X_____XX,_XXX____,
  _XXX__XX,X_____XX,________,
  ______XX,X_____XX,________,
  ______XX,X_____XX,________,
  ______XX,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_6027[ 60] = { /* code 6027 */
  ________,________,________,
  ____XXX_,____XXX_,________,
  ____XX__,____XXX_,________,
  ____XX__,_XX_XXX_,________,
  ____XX__,XXX_XXX_,________,
  ____XXXX,XX__XXX_,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXXX__,XX___XX_,________,
  _XXXXX_X,X____XX_,________,
  _XX_XXXX,_____XX_,________,
  ____XXXX,_____XX_,XX______,
  ____XX__,_____XXX,XX______,
  ____XX__,_XXXXXXX,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_606F[ 60] = { /* code 606F */
  ________,________,________,
  ________,_XX_____,________,
  ________,XX______,________,
  _____XXX,XXXXXXXX,X_______,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XXX,XXXXXXXX,________,
  _____XX_,______XX,________,
  _____XX_,______XX,________,
  _____XXX,XXXXXXXX,________,
  _____XX_,______XX,________,
  _____XXX,XXXXXXXX,________,
  _____XX_,_XX___XX,________,
  ______XX,X_XX___X,X_______,
  ______XX,__XXX___,XXX_____,
  ___XX_XX,___XX___,_XX_____,
  __XXX_XX,______XX,_XXX____,
  __XX__XX,X_____XX,________,
  _______X,XXXXXXX_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_6210[ 60] = { /* code 6210 */
  ________,________,________,
  ________,__XX_XX_,________,
  ________,__XXX_XX,________,
  ________,__XXX__X,X_______,
  ________,__XXX_XX,_XX_____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX__X,XX______,
  ___XXXXX,XXXXX__X,XX______,
  ___XX___,XX_XXX_X,X_______,
  ___XX___,XX__XXXX,X_______,
  ___XX___,XX__XXXX,________,
  ___XX___,XX__XXX_,__XX____,
  ___XX___,XX__XXXX,__XX____,
  __XX__XX,XX_XXXXX,X_XX____,
  __XX___X,X_XXX__X,XXXX____,
  _XX_____,_XX_____,XXXX____,
  _XX_____,XX______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_640F[ 60] = { /* code 640F */
  ________,________,________,
  ____XXX_,____XXXX,X_______,
  ____XX__,____XX_X,XX______,
  ____XX_X,XXXXXXXX,XXX_____,
  ____XXXX,____XX__,________,
  _XXXXXXX,XX__XX__,XX______,
  ____XX__,XXXXXXXX,XX______,
  ____XX__,XX__XX__,XX______,
  ____XX_X,XXXXXXXX,XX______,
  ____XXXX,XX__XX__,XX______,
  ___XXX__,XXXXXXXX,XX______,
  _XXXXX__,XX__XXXX,XX______,
  ____XX_X,X______X,X_______,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,XX_____X,X_______,
  ____XX__,_XXX___X,X_______,
  ____XX__,__XX___X,X_______,
  __XXXX__,____XXXX,X_______,
  ___XX___,______XX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_7387[ 60] = { /* code 7387 */
  ________,________,________,
  ________,_XX_____,________,
  ________,_XXX____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,_XX_____,________,
  ___XX___,XX_____X,X_______,
  ____XX_X,X__XXX_X,X_______,
  ____XXXX,XXXXX_XX,________,
  ________,__XX____,________,
  _____XX_,_XXXX_XX,________,
  ____XX_X,XX__XX_X,XX______,
  __XXX_XX,XXXXXX__,XX______,
  ________,_XXX____,________,
  ________,_XX_____,_XX_____,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_7537[ 60] = { /* code 7537 */
  ________,________,________,
  ____XX__,_______X,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____XX__,_XXX____,________,
  ________,_XXX____,________,
  ________,_XX_____,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ________,_XX_____,XX______,
  ________,XX______,XX______,
  _______X,XX_____X,X_______,
  ______XX,X______X,X_______,
  _____XX_,____XXXX,X_______,
  __XXXX__,_____XXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_75C5[ 60] = { /* code 75C5 */
  ________,________,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ____XXXX,XXXXXXXX,XXX_____,
  _XX_XX__,________,________,
  __XXXX__,________,XX______,
  __XXXX_X,XXXXXXXX,X_______,
  ____XX__,___XXX__,________,
  ____XX__,___XXX__,________,
  ___XXX_X,XXXXXXXX,XXX_____,
  _XXXXX_X,X__XX___,XX______,
  _XX_XX_X,X__XXX__,XX______,
  ____XX_X,X__XXXX_,XX______,
  ____XX_X,X_XX__XX,XX______,
  ___XX__X,XXX___XX,XX______,
  ___XX__X,XX______,XX______,
  __XX___X,X_______,XX______,
  __XX___X,X_____XX,XX______,
  _XX____X,X______X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_7C7B[ 60] = { /* code 7C7B */
  ________,________,________,
  ____XX__,__XX____,________,
  _____XXX,__XX__XX,X_______,
  ______XX,__XX_XX_,________,
  ______XX,__XXXX__,_XX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,XXXXX___,________,
  _______X,X_XXXXXX,X_______,
  ______XX,__XX___X,XX______,
  ____XXX_,__XX____,XXX_____,
  __XXX___,_XX_____,________,
  ________,_XX_____,_XX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,XX_XX___,________,
  ________,XX__XX__,________,
  _______X,X____XX_,________,
  ______XX,______XX,X_______,
  ____XXX_,_______X,XXXX____,
  _XXXX___,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYahei_8109[ 60] = { /* code 8109 */
  ________,________,________,
  ________,____XXX_,________,
  ___XXXXX,X____XXX,________,
  ___XX_XX,_____XX_,________,
  ___XX_XX,_____XX_,________,
  ___XX_XX,__XXXXX_,_XX_____,
  ___XX_XX,_____XX_,_XX_____,
  ___XXXXX,_____XX_,XX______,
  ___XX_XX,XXXXXXXX,X_______,
  ___XX_XX,__XX_XXX,________,
  ___XX_XX,__XX_XXX,________,
  ___XXXXX,__XX_XXX,________,
  ___XX_XX,_XX__XXX,X_______,
  __XX__XX,_XX__XXX,X_______,
  __XX__XX,_XX__XX_,XX______,
  __XX__XX,XX___XX_,XXX_____,
  __XX__XX,X___XXX_,_XX_____,
  _XX__XXX,X_XXXX__,________,
  ________,____XX__,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYahei_CharInfo[25] = {
   {  11,  11,  2, acGUI_FontYahei_0020 } /* code 0020 */
  ,{  11,  11,  2, acGUI_FontYahei_0031 } /* code 0031 */
  ,{  11,  11,  2, acGUI_FontYahei_003A } /* code 003A */
  ,{  21,  21,  3, acGUI_FontYahei_4E09 } /* code 4E09 */
  ,{  21,  21,  3, acGUI_FontYahei_4EBA } /* code 4EBA */
  ,{  21,  21,  3, acGUI_FontYahei_4FE1 } /* code 4FE1 */
  ,{  21,  21,  3, acGUI_FontYahei_522B } /* code 522B */
  ,{  21,  21,  3, acGUI_FontYahei_53F7 } /* code 53F7 */
  ,{  21,  21,  3, acGUI_FontYahei_540D } /* code 540D */
  ,{  21,  21,  3, acGUI_FontYahei_5438 } /* code 5438 */
  ,{  21,  21,  3, acGUI_FontYahei_547C } /* code 547C */
  ,{  21,  21,  3, acGUI_FontYahei_578B } /* code 578B */
  ,{  21,  21,  3, acGUI_FontYahei_59D3 } /* code 59D3 */
  ,{  21,  21,  3, acGUI_FontYahei_5E8A } /* code 5E8A */
  ,{  21,  21,  3, acGUI_FontYahei_5F20 } /* code 5F20 */
  ,{  21,  21,  3, acGUI_FontYahei_5FC3 } /* code 5FC3 */
  ,{  21,  21,  3, acGUI_FontYahei_6027 } /* code 6027 */
  ,{  21,  21,  3, acGUI_FontYahei_606F } /* code 606F */
  ,{  21,  21,  3, acGUI_FontYahei_6210 } /* code 6210 */
  ,{  21,  21,  3, acGUI_FontYahei_640F } /* code 640F */
  ,{  21,  21,  3, acGUI_FontYahei_7387 } /* code 7387 */
  ,{  21,  21,  3, acGUI_FontYahei_7537 } /* code 7537 */
  ,{  21,  21,  3, acGUI_FontYahei_75C5 } /* code 75C5 */
  ,{  21,  21,  3, acGUI_FontYahei_7C7B } /* code 7C7B */
  ,{  21,  21,  3, acGUI_FontYahei_8109 } /* code 8109 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop25 = {
   0x8109 /* first character */
  ,0x8109 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 24] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop24 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontYahei_CharInfo[ 23] /* address of first character */
  ,&GUI_FontYahei_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop23 = {
   0x75C5 /* first character */
  ,0x75C5 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 22] /* address of first character */
  ,&GUI_FontYahei_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop22 = {
   0x7537 /* first character */
  ,0x7537 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 21] /* address of first character */
  ,&GUI_FontYahei_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop21 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 20] /* address of first character */
  ,&GUI_FontYahei_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop20 = {
   0x640F /* first character */
  ,0x640F /* last character  */
  ,&GUI_FontYahei_CharInfo[ 19] /* address of first character */
  ,&GUI_FontYahei_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop19 = {
   0x6210 /* first character */
  ,0x6210 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 18] /* address of first character */
  ,&GUI_FontYahei_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop18 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontYahei_CharInfo[ 17] /* address of first character */
  ,&GUI_FontYahei_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop17 = {
   0x6027 /* first character */
  ,0x6027 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 16] /* address of first character */
  ,&GUI_FontYahei_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop16 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 15] /* address of first character */
  ,&GUI_FontYahei_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop15 = {
   0x5F20 /* first character */
  ,0x5F20 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 14] /* address of first character */
  ,&GUI_FontYahei_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop14 = {
   0x5E8A /* first character */
  ,0x5E8A /* last character  */
  ,&GUI_FontYahei_CharInfo[ 13] /* address of first character */
  ,&GUI_FontYahei_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop13 = {
   0x59D3 /* first character */
  ,0x59D3 /* last character  */
  ,&GUI_FontYahei_CharInfo[ 12] /* address of first character */
  ,&GUI_FontYahei_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop12 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontYahei_CharInfo[ 11] /* address of first character */
  ,&GUI_FontYahei_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop11 = {
   0x547C /* first character */
  ,0x547C /* last character  */
  ,&GUI_FontYahei_CharInfo[ 10] /* address of first character */
  ,&GUI_FontYahei_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop10 = {
   0x5438 /* first character */
  ,0x5438 /* last character  */
  ,&GUI_FontYahei_CharInfo[  9] /* address of first character */
  ,&GUI_FontYahei_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop9 = {
   0x540D /* first character */
  ,0x540D /* last character  */
  ,&GUI_FontYahei_CharInfo[  8] /* address of first character */
  ,&GUI_FontYahei_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop8 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontYahei_CharInfo[  7] /* address of first character */
  ,&GUI_FontYahei_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop7 = {
   0x522B /* first character */
  ,0x522B /* last character  */
  ,&GUI_FontYahei_CharInfo[  6] /* address of first character */
  ,&GUI_FontYahei_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop6 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontYahei_CharInfo[  5] /* address of first character */
  ,&GUI_FontYahei_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop5 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_FontYahei_CharInfo[  4] /* address of first character */
  ,&GUI_FontYahei_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop4 = {
   0x4E09 /* first character */
  ,0x4E09 /* last character  */
  ,&GUI_FontYahei_CharInfo[  3] /* address of first character */
  ,&GUI_FontYahei_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop3 = {
   0x003A /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontYahei_CharInfo[  2] /* address of first character */
  ,&GUI_FontYahei_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop2 = {
   0x0031 /* first character */
  ,0x0031 /* last character  */
  ,&GUI_FontYahei_CharInfo[  1] /* address of first character */
  ,&GUI_FontYahei_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYahei_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontYahei_CharInfo[  0] /* address of first character */
  ,&GUI_FontYahei_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYahei = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYahei_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

